// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaymentApi.Models;

namespace PaymentApi.Migrations
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20200121025208_paymentv2")]
    partial class paymentv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PaymentApi.Models.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("_amount")
                        .HasColumnType("integer");

                    b.Property<string>("_beneficiaryAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("_beneficiaryIfscCode")
                        .HasColumnType("text");

                    b.Property<string>("_beneficiaryName")
                        .HasColumnType("text");

                    b.Property<string>("_payeeAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("_payeeIfscCode")
                        .HasColumnType("text");

                    b.Property<string>("_payeeName")
                        .HasColumnType("text");

                    b.Property<string>("_status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
